title: Site

columns:
  - width: 1/2
    sections:
      workshops: sections/workshops

  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - default

  - width: 2/2
      fields:
        staticSiteGenerator:
          label: Generate a static version of the site
