title: Site

columns:
  - width: 1/2
    sections:
      artists: sections/artists
      workshops: sections/workshops

  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - default
